version: "3.7"
services:
  benzo-prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: benzo-production
    ports:
      - "3000:3000"
  nginx-proxy:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt